jwt:
  secret: bWVnYWJyaWRnZS1ldmVyeW9uZWNhcmUtc3ByaW5nLWJvb3Qtand0LXRva2VuLWRldmVsb3Blci1kZXZnby1kZXZlbG9wZXItZGV2Z28=
  access-token-validity-in-seconds: 1800000
  refresh-token-validity-in-seconds: 2592000000