rootProject:
  name: hackathon

server:
  port: 8888
spring:
  config:
    import:
      - classpath:application-secret.yml
      - classpath:application-database.yml
      - classpath:application-weather.yml
      - classpath:application-removebg.yml
      - classpath:application-chatgpt.yml
      - classpath:application-jwt.yml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379
image:
  allowed-extensions: jpg,png
  max-file-size: 104857600 # 100MB in bytes
  directory: ${user.home}/n5v5w2l_image_storage


springdoc:
  swagger-ui:
    path: /swagger