rootProject:
  name: hackathon

spring:
  config:
    import:
      - classpath:application-secret.yml
      - classpath:application-database.yml
      - classpath:application-weather.yml
      - classpath:application-removebg.yml
      - classpath:application-chatgpt.yml

image:
  allowed-extensions: jpg,png
  max-file-size: 104857600 # 100MB in bytes
  directory: ${user.home}/n5v5w2l_image_storage


springdoc:
  swagger-ui:
    path: /swagger